name: Deploy to Linode

on:
  push:
    branches:
      - master # or main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Deploy files via SCP (contents only)
      - name: Deploy site files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./src/*" # important: contents only
          target: ${{ secrets.DEPLOY_PATH }}
          overwrite: true
