name: Deploy to Linode

on:
  push:
    branches:
      - master # or 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Deploy site files via rsync
      - name: Deploy site files
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            rsync -avz --delete ./src/ ${{ secrets.DEPLOY_PATH }}/
