name: Deploy to Linode via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Deploy via rsync over SSH
      - name: Deploy site files
        run: |
          mkdir -p ${{ secrets.DEPLOY_PATH }}
          rsync -avz --delete ./src/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/
        env:
          RSYNC_RSH: "ssh -i ${{ secrets.DEPLOY_KEY }} -o StrictHostKeyChecking=no"
